# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Kunoh/and3/and3.cache/wt [current_project]
set_property parent.project_path C:/Users/Kunoh/and3/and3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Kunoh/and3/and3.srcs/sources_1/imports/Kunoh/and2/and2.srcs/sources_1/new/and2.vhd
  C:/Users/Kunoh/and3/and3.srcs/sources_1/imports/Kunoh/not1/not1.srcs/sources_1/new/not1.vhd
  C:/Users/Kunoh/and3/and3.srcs/sources_1/new/and3.vhd
  C:/Users/Kunoh/and3/and3.srcs/sources_1/imports/Kunoh/or2/or2.srcs/sources_1/new/or2.vhd
  C:/Users/Kunoh/and3/and3.srcs/sources_1/new/circuit.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Kunoh/and3/and3.srcs/constrs_1/imports/Downloads/ZYBO.xdc
set_property used_in_implementation false [get_files C:/Users/Kunoh/and3/and3.srcs/constrs_1/imports/Downloads/ZYBO.xdc]


synth_design -top circuit -part xc7z010clg400-1


write_checkpoint -force -noxdef circuit.dcp

catch { report_utilization -file circuit_utilization_synth.rpt -pb circuit_utilization_synth.pb }
