######################################################################
#
# File name : and3_wave.do
# Created on: Wed Sep 28 14:23:54 +0200 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
