######################################################################
#
# File name : and2_compile.do
# Created on: Wed Sep 28 14:12:46 +0200 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vcom -64 -2008 -work xil_defaultlib  \
"../../../and2.srcs/sources_1/new/and2.vhd" \


quit -force

