######################################################################
#
# File name : and2_wave.do
# Created on: Wed Sep 28 14:12:47 +0200 2016
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
